name: Test for Node
description: Test resolver on Node

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'
    - name: Run install
      shell: bash
      run: pnpm install
    - name: Run test
      shell: bash
      run: pnpm run test
